old_cat_1__c,old_cat_2__c,old_cat_3__c,old_cat_4__c,old_cat_5__c,new_cat_1__c,new_cat_2__c,new_cat_3__c,new_cat_4__c
Inquiry,Product and Brands,Advertising-Marketing campaign,,,Inquiry,Brand Info (I),Advertising - Marketing Campaign (I),
Inquiry,Product and Brands,Brand use/ Trademark rights,,,Inquiry,Brand Info (I),Brand Use / Trademark Rights,
Inquiry,Product and Brands,Collectors,,,Inquiry,Brand Info (I),Collectors,
Inquiry,Product and Brands,Commercial & Distribution,Beverage distribution,,Inquiry,Commercial & Distribution (I),Beverage Distribution,
Inquiry,Product and Brands,Product info,Sales point - retailer,,Inquiry,Commercial & Distribution (I),Beverage Distribution,
Inquiry,Product and Brands,Commercial & Distribution,Brand advertising materials,,Inquiry,Commercial & Distribution (I),Brand Advertising Materials,
Inquiry,Product and Brands,Commercial & Distribution,Cold Drink Equipment placement,,Inquiry,Commercial & Distribution (I),Cold Drink Equipment Placement,
Inquiry,Product and Brands,Commercial & Distribution,"Commercial, Representative contact",,Inquiry,Commercial & Distribution (I),"Commercial, Representative Contact",
Inquiry,Product and Brands,Commercial & Distribution,Display - Fountain,,Inquiry,Commercial & Distribution (I),Display - Fountain,
Inquiry,Product and Brands,Commercial & Distribution,General,,Inquiry,Commercial & Distribution (I),General,
Inquiry,Product and Brands,Commercial & Distribution,Import - Export,,Inquiry,Commercial & Distribution (I),Import - Export,
Inquiry,Product and Brands,Commercial & Distribution,POS material,,Inquiry,Commercial & Distribution (I),POS Material,
Inquiry,Product and Brands,Commercial & Distribution,Replenishment,,Inquiry,Commercial & Distribution (I),Replenishment,
Inquiry,Product and Brands,Commercial & Distribution,Samples,,Inquiry,Commercial & Distribution (I),Samples,
Inquiry,Product and Brands,Commercial & Distribution,Suppliers,,Inquiry,Commercial & Distribution (I),Suppliers,
Inquiry,Corporate,Boycott,,,Inquiry,Corporate (I),Boycott (I),
Inquiry,Corporate,Brochure,,,Inquiry,Corporate (I),Brochure,
Inquiry,Corporate,Corporate Citizenship,,,Inquiry,Corporate (I),Corporate Citizenship,
Inquiry,Corporate,Environment - Recycling,,,Inquiry,Corporate (I),Environment - Recycling,
Inquiry,Corporate,Foreign issues,,,Inquiry,Corporate (I),Foreign Issues,
Inquiry,Corporate,General info,,,Inquiry,Corporate (I),General Info,
Inquiry,Corporate,Interview,,,Inquiry,Corporate (I),Interview,
Inquiry,Corporate,Jobs@coke,,,Inquiry,Corporate (I),Jobs@coke,
Inquiry,Corporate,Organization,,,Inquiry,Corporate (I),Organization,
Inquiry,Corporate,Patronage,,,Inquiry,Corporate (I),Patronage,Local Event (Patronage I)
Inquiry,Corporate,Plant visit,,,Inquiry,Corporate (I),Plant Visit,
Inquiry,Corporate,Pricing,,,Inquiry,Corporate (I),Pricing,
Inquiry,Corporate,Rumors-Polemics,Environment,,Inquiry,Corporate (I),Rumors-Polemics (I),Environment (I)
Inquiry,Corporate,Corporate Rumors & Polemics,,,Inquiry,Corporate (I),Rumors-Polemics (I),Other (Rumors-Polemics I)
Inquiry,Corporate,Miscellaneous corporate,Religion - Politics,,Inquiry,Corporate (I),Rumors-Polemics (I),Religion - Politics (I)
Inquiry,Corporate,Rumors-Polemics,Spamming,,Inquiry,Corporate (I),Rumors-Polemics (I),Spamming (I)
Inquiry,Corporate,Social,,,Inquiry,Corporate (I),Social (I),
Inquiry,Corporate,Threat,,,Inquiry,Corporate (I),Threat,
Inquiry,Health and Nutrition,ADI,,,Inquiry,Health and Nutrition (I),Acceptable Daily Intake,
Inquiry,Health and Nutrition,Allergies,Gluten,,Inquiry,Health and Nutrition (I),Allergies,Gluten
Inquiry,Health and Nutrition,Allergies,Milk,,Inquiry,Health and Nutrition (I),Allergies,Milk
Inquiry,Health and Nutrition,Allergies,Other,,Inquiry,Health and Nutrition (I),Allergies,Other (Allergies I)
Inquiry,Health and Nutrition,Caries,,,Inquiry,Health and Nutrition (I),Caries / Cavities / Dental Health,
Inquiry,Health and Nutrition,Consumption age,,,Inquiry,Health and Nutrition (I),Consumption Age,
Inquiry,Health and Nutrition,Dietary advice,,,Inquiry,Health and Nutrition (I),Dietary Advice,
Inquiry,Health and Nutrition,GDA,,,Inquiry,Health and Nutrition (I),Guideline Daily Amount,
Inquiry,Health and Nutrition,Health Rumors & Polemics,,,Inquiry,Health and Nutrition (I),Health Rumors & Polemics,
Inquiry,Health and Nutrition,Casher-Hallal,,,Inquiry,Health and Nutrition (I),Kosher-Hallal (I),
Inquiry,Health and Nutrition,Miscellaneous health,,,Inquiry,Health and Nutrition (I),Miscellaneous Health,
Inquiry,Health and Nutrition,Pathologies,Cancer,,Inquiry,Health and Nutrition (I),Pathologies,Cancer
Inquiry,Health and Nutrition,Allergies Pathologies,Celiac,,Inquiry,Health and Nutrition (I),Pathologies,Celiac
Inquiry,Health and Nutrition,Pathologies,Diabetes,,Inquiry,Health and Nutrition (I),Pathologies,Diabetes
Inquiry,Health and Nutrition,Allergies Pathologies,Phenylalaninae/Phenylcetonurie,,Inquiry,Health and Nutrition (I),Pathologies,Phenylalanine / Phenylcetonurie
Inquiry,Health and Nutrition,Pregnancy Advice,,,Inquiry,Health and Nutrition (I),Pregnancy Advice,
Inquiry,Health and Nutrition,Sweeteners,,,Inquiry,Health and Nutrition (I),Sweeteners (I),
Inquiry,Health and Nutrition,Weight- Obesity,,,Inquiry,Health and Nutrition (I),Weight - Obesity,
Inquiry,Product and Brands,Press Release,,,Inquiry,Press Release,,
Inquiry,Product and Brands,Product info,Best Before date,,Inquiry,Product Info (I),Best Before Date,
Inquiry,Product and Brands,Product info,Calories,,Inquiry,Product Info (I),Calories,
Inquiry,Product and Brands,Product info,conservation and/or consumption condition,,Inquiry,Product Info (I),Conservation or Consumption Condition,
Inquiry,Product and Brands,Experiential sampling,,,Inquiry,Product Info (I),Experiential Sampling,
Inquiry,Product and Brands,Product info,Formula - Ingredients,Ace-K,Inquiry,Product Info (I),Formula - Ingredients,Ace-K
Inquiry,Product and Brands,Product info,Formula - Ingredients,Acidifyer,Inquiry,Product Info (I),Formula - Ingredients,Acidifyer
Inquiry,Product and Brands,Product info,Formula - Ingredients,Alcohol,Inquiry,Product Info (I),Formula - Ingredients,Alcohol
Inquiry,Product and Brands,Product info,Formula - Ingredients,Aspartame,Inquiry,Product Info (I),Formula - Ingredients,Aspartame
Inquiry,Product and Brands,Product info,Formula - Ingredients,BPA,Inquiry,Product Info (I),Formula - Ingredients,Bisphenol A (BPA)
Inquiry,Product and Brands,Product info,Formula - Ingredients,Caffeine,Inquiry,Product Info (I),Formula - Ingredients,Caffeine
Inquiry,Product and Brands,Product info,Formula - Ingredients,Calcium,Inquiry,Product Info (I),Formula - Ingredients,Calcium
Inquiry,Product and Brands,Product info,Formula - Ingredients,Calories,Inquiry,Product Info (I),Formula - Ingredients,Calories
Inquiry,Product and Brands,Product info,Formula - Ingredients,Caramel,Inquiry,Product Info (I),Formula - Ingredients,Caramel
Inquiry,Product and Brands,Product info,Formula - Ingredients,Carbohydrates,Inquiry,Product Info (I),Formula - Ingredients,Carbohydrates
Inquiry,Product and Brands,Product info,Formula - Ingredients,CO2,Inquiry,Product Info (I),Formula - Ingredients,CO2
Inquiry,Product and Brands,Product info,Formula - Ingredients,Cyclamate,Inquiry,Product Info (I),Formula - Ingredients,Cyclamate
Inquiry,Product and Brands,Product info,Formula - Ingredients,E numbers,Inquiry,Product Info (I),Formula - Ingredients,E Numbers
Inquiry,Product and Brands,Product info,Formula - Ingredients,Fat,Inquiry,Product Info (I),Formula - Ingredients,Fat
Inquiry,Product and Brands,Product info,Formula - Ingredients,Fibres,Inquiry,Product Info (I),Formula - Ingredients,Fibres
Inquiry,Product and Brands,Product info,Formula - Ingredients,Flavours & Colouring,Inquiry,Product Info (I),Formula - Ingredients,Flavours & Colouring
Inquiry,Product and Brands,Product info,Formula - Ingredients,Food additives,Inquiry,Product Info (I),Formula - Ingredients,Food Additives
Inquiry,Product and Brands,Product info,Formula - Ingredients,HFCS (High Fructose Corn Syrup),Inquiry,Product Info (I),Formula - Ingredients,HFCS (High Fructose Corn Syrup)
Inquiry,Product and Brands,Product info,Formula - Ingredients,Miscellaneous,Inquiry,Product Info (I),Formula - Ingredients,Miscellaneous
Inquiry,Product and Brands,Product info,Formula - Ingredients,Other,Inquiry,Product Info (I),Formula - Ingredients,Other (Formula - Ingredients I)
Inquiry,Product and Brands,Product info,Formula - Ingredients,Phosphoric acid,Inquiry,Product Info (I),Formula - Ingredients,Phosphoric Acid
Inquiry,Product and Brands,Product info,Formula - Ingredients,Phosporus,Inquiry,Product Info (I),Formula - Ingredients,Phosporus
Inquiry,Product and Brands,Product info,Formula - Ingredients,Potassium,Inquiry,Product Info (I),Formula - Ingredients,Potassium
Inquiry,Product and Brands,Product info,Formula - Ingredients,Preservatives,Inquiry,Product Info (I),Formula - Ingredients,Preservatives
Inquiry,Product and Brands,Product info,Formula - Ingredients,Proteins,Inquiry,Product Info (I),Formula - Ingredients,Proteins
Inquiry,Product and Brands,Product info,Formula - Ingredients,Quinine,Inquiry,Product Info (I),Formula - Ingredients,Quinine
Inquiry,Product and Brands,Product info,Formula - Ingredients,Saccharine,Inquiry,Product Info (I),Formula - Ingredients,Saccharine
Inquiry,Product and Brands,Product info,Formula - Ingredients,Scents,Inquiry,Product Info (I),Formula - Ingredients,Scents
Inquiry,Product and Brands,Product info,Formula - Ingredients,Sodium (salt),Inquiry,Product Info (I),Formula - Ingredients,Sodium (Salt)
Inquiry,Product and Brands,Product info,Formula - Ingredients,Stevia,Inquiry,Product Info (I),Formula - Ingredients,Stevia
Inquiry,Product and Brands,Product info,Formula - Ingredients,Sugar,Inquiry,Product Info (I),Formula - Ingredients,Sugar
Inquiry,Product and Brands,Product info,Formula - Ingredients,Taurine,Inquiry,Product Info (I),Formula - Ingredients,Taurine
Inquiry,Product and Brands,Product info,Formula - Ingredients,Theine,Inquiry,Product Info (I),Formula - Ingredients,Theine
Inquiry,Product and Brands,Product info,Formula - Ingredients,Vitamines,Inquiry,Product Info (I),Formula - Ingredients,Vitamines
Inquiry,Product and Brands,Product info,General composition,,Inquiry,Product Info (I),General Composition,
Inquiry,Product and Brands,Product info,Packaging,,Inquiry,Product Info (I),Packaging,
Inquiry,Product and Brands,Product info,Presence,"Pork, animal traces",Inquiry,Product Info (I),Presence,"Pork, Animal Traces"
Inquiry,Product and Brands,Product info,Producted not marketed locally,,Inquiry,Product Info (I),Product not Marketed Locally,
Inquiry,Product and Brands,Product placement,,,Inquiry,Product Info (I),Product Placement,
Inquiry,Product and Brands,Product info,Quantity,,Inquiry,Product Info (I),Quantity,
Inquiry,Product and Brands,Product info,Promotion,Cnil-Opt Out,Inquiry,Promotion (I),Cnil-Opt Out,
Inquiry,Product and Brands,Product info,Promotion,Mecanism - Explanation,Inquiry,Promotion (I),Mechanism - Explanation,
Inquiry,Product and Brands,Product info,Promotion,Prize Collection,Inquiry,Promotion (I),Prize Collection,
Inquiry,Product and Brands,Product info,Promotion,Rules,Inquiry,Promotion (I),Rules,
Inquiry,Product and Brands,Product info,Promotion,SMS / Promotion Code Generation,Inquiry,Promotion (I),SMS / Promotion Code Generation,
Inquiry,Sponsoring,Commercial proposals,,,Inquiry,Sponsoring,Commercial Proposals,
Inquiry,Sponsoring,Local event,,,Inquiry,Sponsoring,Miscellaneous Sponsoring,Local Event (Miscellaneous Sponsoring I)
Inquiry,Sponsoring,Miscellaneous sponsoring,,,Inquiry,Sponsoring,Miscellaneous Sponsoring,National Event (Miscellaneous Sponsoring I)
Inquiry,Sponsoring,National event,,,Inquiry,Sponsoring,Miscellaneous Sponsoring,National Event (Miscellaneous Sponsoring I)
Inquiry,Sponsoring,Partnership,Music events,,Inquiry,Sponsoring,Music Events,National Event (Music Events I)
Inquiry,Sponsoring,"Request coupons, vouchers",,,Inquiry,Sponsoring,"Request Coupons, Vouchers",
Inquiry,Sponsoring,Request gadgets,,,Inquiry,Sponsoring,Request Gadgets,
Inquiry,Sponsoring,Request products,,,Inquiry,Sponsoring,Request Products,
Inquiry,Sponsoring,School fairs,,,Inquiry,Sponsoring,School Fairs,
Inquiry,Sponsoring,Partnership,Sports events,,Inquiry,Sponsoring,Sports Events,National Event (Sports Events I)
Inquiry,Product and Brands,Product info,Suggestion,,Inquiry,Suggestion,Other (Suggestion I),
Joke / Useless,Hang up,,,,Joke / Useless,Hang up,,
Joke / Useless, Insults,,,,Joke / Useless,Insults,,
Joke / Useless,Wrong Number,,,,Joke / Useless,Wrong Number,,
Non-Quality Complaint,Marketing,Advertising - Marketing campaign,,,Non-Quality Complaint,Brand Info (nonQ),Advertising - Marketing Campaign (nonQ),
Non-Quality Complaint,Marketing,Expensive products pricing,,,Non-Quality Complaint,Brand Info (nonQ),Expensive Products Pricing,
Non-Quality Complaint,Commercial & Distribution,Customer quality complaints,,,Non-Quality Complaint,Commercial & Distribution (nonQ),Customer Quality Complaints,
Non-Quality Complaint,Commercial & Distribution,"Display, Cold materials dysfunction",,,Non-Quality Complaint,Commercial & Distribution (nonQ),"Display, Cold Materials Dysfunction",
Non-Quality Complaint,Commercial & Distribution,Imported product,Labelling,,Non-Quality Complaint,Commercial & Distribution (nonQ),Imported Product,Labelling
Non-Quality Complaint,Commercial & Distribution,Imported product,Quality,,Non-Quality Complaint,Commercial & Distribution (nonQ),Imported Product,Quality (Imported Product nonQ)
Non-Quality Complaint,Commercial & Distribution,Invoice,,,Non-Quality Complaint,Commercial & Distribution (nonQ),Invoice,
Non-Quality Complaint,Commercial & Distribution,Product,Expired Product,,Non-Quality Complaint,Commercial & Distribution (nonQ),Product (nonQ),Expired Product
Non-Quality Complaint,Commercial & Distribution,Product bought abroad,Quality,,Non-Quality Complaint,Commercial & Distribution (nonQ),Product Bought Abroad,Quality (Product Bought Abroad nonQ)
Non-Quality Complaint,Commercial & Distribution,Promotion,,,Non-Quality Complaint,Commercial & Distribution (nonQ),Promotion (nonQ),
Non-Quality Complaint,Commercial & Distribution,Sales representative avalability,,,Non-Quality Complaint,Commercial & Distribution (nonQ),Sales Representative Availability,
Non-Quality Complaint,Commercial & Distribution,Vending machine,Currency not issued,,Non-Quality Complaint,Commercial & Distribution (nonQ),Vending Machine,Currency not Issued
Non-Quality Complaint,Commercial & Distribution,Vending machine,Currency not issued and product not delivered,,Non-Quality Complaint,Commercial & Distribution (nonQ),Vending Machine,Currency not Issued and Product not Delivered
Non-Quality Complaint,Commercial & Distribution,Vending machine,Others products delivered,,Non-Quality Complaint,Commercial & Distribution (nonQ),Vending Machine,Others Products Delivered
Non-Quality Complaint,Commercial & Distribution,Vending machine,Product not delivered,,Non-Quality Complaint,Commercial & Distribution (nonQ),Vending Machine,Product not Delivered
Non-Quality Complaint,Commercial & Distribution,Vending machine,Vending Machine dysfunction,,Non-Quality Complaint,Commercial & Distribution (nonQ),Vending Machine,Vending Machine Dysfunction
Non-Quality Complaint,Corporate,Boycott,,,Non-Quality Complaint,Corporate (nonQ),Boycott (nonQ),
Non-Quality Complaint,Corporate,Other,,,Non-Quality Complaint,Corporate (nonQ),Other (Corporate nonQ),
Non-Quality Complaint,Corporate,Rumors-Polemics,Environment,,Non-Quality Complaint,Corporate (nonQ),Rumors-Polemics (nonQ),Environment (nonQ)
Non-Quality Complaint,Corporate,Rumors-Polemics,Religion - Politics,,Non-Quality Complaint,Corporate (nonQ),Rumors-Polemics (nonQ),Religion - Politics (nonQ)
Non-Quality Complaint,Corporate,Rumors-Polemics,Spamming,,Non-Quality Complaint,Corporate (nonQ),Rumors-Polemics (nonQ),Spamming (nonQ)
Non-Quality Complaint,Corporate,Social,,,Non-Quality Complaint,Corporate (nonQ),Social (nonQ),
Non-Quality Complaint,Corporate,Threat - Blackmail,,,Non-Quality Complaint,Corporate (nonQ),Threat - Blackmail,
Non-Quality Complaint,Material damages,,,,Non-Quality Complaint,Material Damages,,
Non-Quality Complaint,Marketing,Product formula,,,Non-Quality Complaint,Product Info (nonQ),Product Formula,
Non-Quality Complaint,Promotion,Difficulties of participation,"Lack of clarity of mecanism, rules",,Non-Quality Complaint,Promotion (nonQ),Difficulties of Participation,"Lack of Clarity of Mechanism, Rules"
Non-Quality Complaint,Promotion,Difficulties of participation,Promotion not present on sales point involved,,Non-Quality Complaint,Promotion (nonQ),Difficulties of Participation,Promotion not Present on Sales Point Involved
Non-Quality Complaint,Promotion,Difficulties of participation,Technical difficulties,,Non-Quality Complaint,Promotion (nonQ),Difficulties of Participation,Technical Difficulties
Non-Quality Complaint,Promotion,Item not received,,,Non-Quality Complaint,Promotion (nonQ),Item / Prize not Received,
Non-Quality Complaint,Promotion,Item quality,Goodies with default,,Non-Quality Complaint,Promotion (nonQ),Item Quality,Goodies with Default
Non-Quality Complaint,Promotion,Product removed from packaging,,,Non-Quality Complaint,Promotion (nonQ),Product Removed from Packaging,
Quality Complaint,Products,Package Quality,Body injuries,,Quality Complaint,Package Quality,Body Injuries,
Quality Complaint,Products,Package Quality,"Closure, Pour panel",Closure damaged,Quality Complaint,Package Quality,"Closure, Pour Panel",Closure Damaged
Quality Complaint,Products,Package Quality,"Closure, Pour panel","Defective closure application (loose, misapplied, defective foil seal)",Quality Complaint,Package Quality,"Closure, Pour Panel","Defective Closure Application (Loose, Misapplied, Defective Foil Seal)"
Quality Complaint,Products,Package Quality,"Closure, Pour panel",Fails to open,Quality Complaint,Package Quality,"Closure, Pour Panel",Fails to Open
Quality Complaint,Products,Package Quality,"Closure, Pour panel",Hard to open or high torque,Quality Complaint,Package Quality,"Closure, Pour Panel",Hard to Open or High Torque
Quality Complaint,Products,Package Quality,"Closure, Pour panel",Missing parts,Quality Complaint,Package Quality,"Closure, Pour Panel",Missing Parts
Quality Complaint,Products,Package Quality,"Closure, Pour panel",Nozzle defective or fell off (BIB),Quality Complaint,Package Quality,"Closure, Pour Panel",Nozzle Defective or Fell off (BIB)
Quality Complaint,Products,Package Quality,"Closure, Pour panel","Open spontaneously , accidentally(e.g. tab of a can, closure blow offs)",Quality Complaint,Package Quality,"Closure, Pour Panel","Open Spontaneously, Accidentally (e.g. tab of a can, closure blow offs)"
Quality Complaint,Products,Package Quality,"Closure, Pour panel",Other closure/pour panel,Quality Complaint,Package Quality,"Closure, Pour Panel","Other (Closure, Pour Panel Q)"
Quality Complaint,Products,Package Quality,"Closure, Pour panel","Pilfer, tamper-evident band or ring broken or missing",Quality Complaint,Package Quality,"Closure, Pour Panel","Pilfer, Tamper-Evident Band or Ring Broken or Missing"
Quality Complaint,Products,Package Quality,"Closure, Pour panel","Pilfer, tamper-evident band or ring didn't break regularly",Quality Complaint,Package Quality,"Closure, Pour Panel","Pilfer, Tamper-Evident Band or Ring didn't Break Regularly"
Quality Complaint,Products,Package Quality,"Closure, Pour panel",Rusty/dirty,Quality Complaint,Package Quality,"Closure, Pour Panel",Rusty / Dirty
Quality Complaint,Products,Package Quality,"Closure, Pour panel","Sharp edge at pour panel, container end defect, chipped",Quality Complaint,Package Quality,"Closure, Pour Panel","Sharp Edge at Pour Panel, Container End Defect, Chipped"
Quality Complaint,Products,Package Quality,Container Bulge/Exploding,Bottom or Dome reversal (e.g. of a can),Quality Complaint,Package Quality,Container Bulge,Bottom or Dome Reversal (e.g. of a can)
Quality Complaint,Products,Package Quality,Container Bulge/Exploding,Deformed container,Quality Complaint,Package Quality,Container Bulge,Deformed Container
Quality Complaint,Products,Package Quality,Container Damage,Neck or neck support,Quality Complaint,Package Quality,Container Bulge,Neck or Neck Support
Quality Complaint,Products,Package Quality,Container Bulge/Exploding,Neck support,Quality Complaint,Package Quality,Container Bulge,Neck or Neck Support
Quality Complaint,Products,Package Quality,Container Bulge/Exploding,Other container bulge/exploding,Quality Complaint,Package Quality,Container Bulge,Other Container Bulge / Exploding
Quality Complaint,Products,Package Quality,Container Bulge/Exploding,Soft sided,Quality Complaint,Package Quality,Container Bulge,Soft Sided
Quality Complaint,Products,Package Quality,Container Bulge/Exploding,"Top and bottom bulge, pumped up. Peaked",Quality Complaint,Package Quality,Container Bulge,"Top and Bottom Bulge, Pumped up. Peaked"
Quality Complaint,Products,Package Quality,Container Damage,Bottom damaged,Quality Complaint,Package Quality,Container Damage,Bottom
Quality Complaint,Products,Package Quality,Container Damage,Broken,Quality Complaint,Package Quality,Container Damage,Broken
Quality Complaint,Products,Package Quality,Container Damage,Broken finish,Quality Complaint,Package Quality,Container Damage,Broken Finish
Quality Complaint,Products,Package Quality,Container Bulge/Exploding,Exploding bottom of container,Quality Complaint,Package Quality,Container Damage,Burst / Exploding - Unknown
Quality Complaint,Products,Package Quality,Container Bulge/Exploding,Exploding side of container,Quality Complaint,Package Quality,Container Damage,Burst / Exploding - Unknown
Quality Complaint,Products,Package Quality,Container Bulge/Exploding,Exploding top of container,Quality Complaint,Package Quality,Container Damage,Burst / Exploding - Unknown
Quality Complaint,Products,Package Quality,Container Damage,Burst/exploding - cold or hot abuse,Quality Complaint,Package Quality,Container Damage,Burst / Exploding - Unknown
Quality Complaint,Products,Package Quality,Container Damage,Crushed,Quality Complaint,Package Quality,Container Damage,Crushed
Quality Complaint,Products,Package Quality,Container Damage,Leaner/distorted,Quality Complaint,Package Quality,Container Damage,Leaner / Distorted
Quality Complaint,Products,Package Quality,Container Damage,Other damage,Quality Complaint,Package Quality,Container Damage,Other (Container Damage Q)
Quality Complaint,Products,Package Quality,Container Damage,Rusty container,Quality Complaint,Package Quality,Container Damage,Rusty Container
Quality Complaint,Products,Package Quality,Container Damage,Scuffed or scratched,Quality Complaint,Package Quality,Container Damage,Scuffed or Scratched
Quality Complaint,Products,Package Quality,Container Damage,Sharp edges,Quality Complaint,Package Quality,Container Damage,Sharp Edges
Quality Complaint,Products,Package Quality,Container Damage,Side or body wall,Quality Complaint,Package Quality,Container Damage,Side (Container Damage Q)
Quality Complaint,Products,Package Quality,Container Damage,Top damaged,Quality Complaint,Package Quality,Container Damage,Top (Container Damage Q)
Quality Complaint,Products,Package Quality,Container leak,Can end score line hole,Quality Complaint,Package Quality,Container Leaker,Can End Score Line Hole
Quality Complaint,Products,Package Quality,Container leak,Closure or crown damage,Quality Complaint,Package Quality,Container Leaker,Closure or Crown Damage
Quality Complaint,Products,Package Quality,Container leak,Container valve,Quality Complaint,Package Quality,Container Leaker,Container Valve / Connector
Quality Complaint,Products,Package Quality,Container leak,Can corrosion (e.g. secondary corrosion),Quality Complaint,Package Quality,Container Leaker,Corrosion
Quality Complaint,Products,Package Quality,Container leak,External pin hole,Quality Complaint,Package Quality,Container Leaker,External Pin Hole
Quality Complaint,Products,Package Quality,Container leak,Other leak,Quality Complaint,Package Quality,Container Leaker,Other (Container Leaker Q)
Quality Complaint,Products,Package Quality,Container leak,Rivet leaker of a can,Quality Complaint,Package Quality,Container Leaker,Rivet Leaker of a Can
Quality Complaint,Products,Package Quality,Container leak,Seam,Quality Complaint,Package Quality,Container Leaker,Seam
Quality Complaint,Products,Package Quality,Container leak,Side,Quality Complaint,Package Quality,Container Leaker,Side (Container Leaker Q)
Quality Complaint,Products,Package Quality,Container leak,Top leaks,Quality Complaint,Package Quality,Container Leaker,Top (Container Leaker Q)
Quality Complaint,Products,Package Quality,Dirty container,Glue,Quality Complaint,Package Quality,Dirty Container,Glue
Quality Complaint,Products,Package Quality,Dirty container,Greasy,Quality Complaint,Package Quality,Dirty Container,Greasy
Quality Complaint,Products,Package Quality,Dirty container,Mould,Quality Complaint,Package Quality,Dirty Container,Mould
Quality Complaint,Products,Package Quality,Dirty container,"Odour, musty",Quality Complaint,Package Quality,Dirty Container,Odour
Quality Complaint,Products,Package Quality,Dirty container,Dirty secondary packaging,Quality Complaint,Package Quality,Dirty Container,Other (Dirty Container Q)
Quality Complaint,Products,Package Quality,Dirty container,"Other, general dirty",Quality Complaint,Package Quality,Dirty Container,Other (Dirty Container Q)
Quality Complaint,Products,Package Quality,Dirty container,Sticky,Quality Complaint,Package Quality,Dirty Container,Sticky
Quality Complaint,Products,Package Quality,Fill level,Empty container,Quality Complaint,Package Quality,Fill Control,Empty Container
Quality Complaint,Products,Package Quality,Fill level,"Overfilled, high fill",Quality Complaint,Package Quality,Fill Control,Overfilled
Quality Complaint,Products,Package Quality,Fill level,Short filled or partially filled or under half fill level,Quality Complaint,Package Quality,Fill Control,Short Filled
Quality Complaint,Products,Package Quality,Incomplete Packaging,Broken handle secondary packaging,Quality Complaint,Package Quality,Incomplete Packaging,Handle Missing
Quality Complaint,Products,Package Quality,Incomplete Packaging,Incorrect product,Quality Complaint,Package Quality,Incomplete Packaging,Incorrect Product
Quality Complaint,Products,Package Quality,Incomplete Packaging,Missing package (e.g. unit is missing in a multipack),Quality Complaint,Package Quality,Incomplete Packaging,M/P Unit is Missing
Quality Complaint,Products,Package Quality,Incomplete Packaging,Missing handle secondary packaging,Quality Complaint,Package Quality,Incomplete Packaging,Missing Handle Secondary Packaging
Quality Complaint,Products,Package Quality,Incomplete Packaging,Other incomplete,Quality Complaint,Package Quality,Incomplete Packaging,Other (Incomplete Packaging Q)
Quality Complaint,Products,Package Quality,Incomplete Packaging,Straw missing,Quality Complaint,Package Quality,Incomplete Packaging,Straw Missing
Quality Complaint,Products,Package Quality,Label,Double,Quality Complaint,Package Quality,Label,Double
Quality Complaint,Products,Package Quality,Label,Misaligned or misapplied,Quality Complaint,Package Quality,Label,Misaligned or Misapplied
Quality Complaint,Products,Package Quality,Label,Missing,Quality Complaint,Package Quality,Label,Missing
Quality Complaint,Products,Package Quality,Label,Not legible ingredient declaration,Quality Complaint,Package Quality,Label,Not Legible
Quality Complaint,Products,Package Quality,Label,Damaged,Quality Complaint,Package Quality,Label,Other (Label Q)
Quality Complaint,Products,Package Quality,Label,Other (label),Quality Complaint,Package Quality,Label,Other (Label Q)
Quality Complaint,Products,Package Quality,Label,Torn,Quality Complaint,Package Quality,Label,Torn
Quality Complaint,Products,Package Quality,Label,Upside down,Quality Complaint,Package Quality,Label,Upside Down
Quality Complaint,Products,Package Quality,Label,Wrong or incorrect label,Quality Complaint,Package Quality,Label,Wrong Label
Quality Complaint,Products,Package Quality,Other,,Quality Complaint,Package Quality,Other (Package Quality Q),
Quality Complaint,Products,Package Quality,Other pack faults,Date code hard to read or misleading,Quality Complaint,Package Quality,Other Pack Faults,Code Hard to Read / Misleading
Quality Complaint,Products,Package Quality,Other pack faults,"Color, paintwork",Quality Complaint,Package Quality,Other Pack Faults,"Color, Paintwork"
Quality Complaint,Products,Package Quality,Other pack faults,Date code Missing,Quality Complaint,Package Quality,Other Pack Faults,Date Code Missing
Quality Complaint,Products,Package Quality,Other pack faults,Multipack film misaligned,Quality Complaint,Package Quality,Other Pack Faults,Multipack Film Misaligned
Quality Complaint,Products,Package Quality,Other pack faults,Other defects (describe),Quality Complaint,Package Quality,Other Pack Faults,Other (Other Pack Faults Q)
Quality Complaint,Products,Package Quality,Other pack faults,Other primary packaging defect,Quality Complaint,Package Quality,Other Pack Faults,Other Primary Packaging Defect
Quality Complaint,Products,Package Quality,Other pack faults,Other secondary packaging defect,Quality Complaint,Package Quality,Other Pack Faults,Other Secondary Packaging Defect
Quality Complaint,Products,Product Quality,Carbonatation,Gushing (excesive foaming),Quality Complaint,Product Quality,Carbonation,Gushes / Overcarbonation
Quality Complaint,Products,Product Quality,Carbonatation,"Product overcarbonated, too fizzy",Quality Complaint,Product Quality,Carbonation,Gushes / Overcarbonation
Quality Complaint,Products,Product Quality,Carbonatation,"Product flat, low carbonated",Quality Complaint,Product Quality,Carbonation,Product Flat on Opening
Quality Complaint,Products,Product Quality,Foreign matter,"Capsule, drug, pills, tablet",Quality Complaint,Product Quality,Foreign Matter,"Capsule, Drug, Pills, Tablet"
Quality Complaint,Products,Product Quality,Foreign matter,"Cloth, textile like",Quality Complaint,Product Quality,Foreign Matter,"Cloth, Textile Like"
Quality Complaint,Products,Product Quality,Foreign matter,Glass like,Quality Complaint,Product Quality,Foreign Matter,Glass Like Sample Unopened
Quality Complaint,Products,Product Quality,Foreign matter,"Organic like (insects, roedents, other organic material, vegetables, food, dirt)",Quality Complaint,Product Quality,Foreign Matter,Insect Like
Quality Complaint,Products,Product Quality,Foreign matter,Label like,Quality Complaint,Product Quality,Foreign Matter,Label Like
Quality Complaint,Products,Product Quality,Foreign matter,"Metallic or ferrous like (needel, machinry pieces, pull tab, crown, etc)",Quality Complaint,Product Quality,Foreign Matter,Metal Like
Quality Complaint,Products,Product Quality,Foreign matter,Mould or gelatine like,Quality Complaint,Product Quality,Foreign Matter,Mould or Gelatine Like
Quality Complaint,Products,Product Quality,Foreign matter,Other material,Quality Complaint,Product Quality,Foreign Matter,Other Material
Quality Complaint,Products,Product Quality,Foreign matter,Paper like,Quality Complaint,Product Quality,Foreign Matter,Paper Like
Quality Complaint,Products,Product Quality,Foreign matter,"Plastic like (srying, tamper evident band, straw, others)",Quality Complaint,Product Quality,Foreign Matter,Plastic Like (Foreign Matter Q)
Quality Complaint,Products,Product Quality,Foreign matter,Rubber like,Quality Complaint,Product Quality,Foreign Matter,Rubber Like
Quality Complaint,Products,Product Quality,Foreign matter,Sediment unidentified,Quality Complaint,Product Quality,Foreign Matter,Sediment
Quality Complaint,Products,Product Quality,Colour/ Appearance,Lumpy,Quality Complaint,Product Quality,Foreign Matter,"Suspended, Floating Material (Floc)"
Quality Complaint,Products,Product Quality,Foreign matter,"Suspended, floating material (floc)",Quality Complaint,Product Quality,Foreign Matter,"Suspended, Floating Material (Floc)"
Quality Complaint,Products,Product Quality,Foreign matter,"Tobacco, ashes, cigarret",Quality Complaint,Product Quality,Foreign Matter,"Tobacco, Cigarette"
Quality Complaint,Products,Product Quality,Foreign matter,Wood like,Quality Complaint,Product Quality,Foreign Matter,Wood Like
Quality Complaint,Products,Product Quality,Body Injuries,Illness,Quality Complaint,Product Quality,Illness,Illness (Q)
Quality Complaint,Products,Product Quality,Body Injuries,Physical injuries,Quality Complaint,Product Quality,Injury,Physical Injuries
Quality Complaint,Products,Product Quality,Colour/ Appearance,Loss of cloudiness (when expected cloudy beverage),Quality Complaint,Product Quality,Off Colour / Appearance,Clear (When Expected Cloudy)
Quality Complaint,Products,Product Quality,Colour/ Appearance,Cloudy (when expected clear),Quality Complaint,Product Quality,Off Colour / Appearance,Cloudy (When Expected Clear)
Quality Complaint,Products,Product Quality,Colour/ Appearance,Color deviation - darker than expected,Quality Complaint,Product Quality,Off Colour / Appearance,Darker than Expected
Quality Complaint,Products,Product Quality,Colour/ Appearance,"Color deviation - lighter than expected, faded",Quality Complaint,Product Quality,Off Colour / Appearance,"Lighter than Expected, Faded"
Quality Complaint,Products,Product Quality,Colour/ Appearance,Neck ring or surface ring/package surface deposit,Quality Complaint,Product Quality,Off Colour / Appearance,Neck Ring or Surface Ring / Package Surface Deposit
Quality Complaint,Products,Product Quality,Colour/ Appearance,No pulpy (when expected pulpy),Quality Complaint,Product Quality,Off Colour / Appearance,No Pulpy (When Expected Pulpy)
Quality Complaint,Products,Product Quality,Colour/ Appearance,Oil or grease or gazoline or petrol,Quality Complaint,Product Quality,Off Colour / Appearance,Oil or Grease or Gazoline or Petrol
Quality Complaint,Products,Product Quality,Colour/ Appearance,Other color deviation,Quality Complaint,Product Quality,Off Colour / Appearance,Other (Off Colour / Appearance Q)
Quality Complaint,Products,Product Quality,Colour/ Appearance,Other colour/appearance,Quality Complaint,Product Quality,Off Colour / Appearance,Other (Off Colour / Appearance Q)
Quality Complaint,Products,Product Quality,Colour/ Appearance,Separated phases: floating or sedimented,Quality Complaint,Product Quality,Off Colour / Appearance,Separated
Quality Complaint,Products,Product Quality,Colour/ Appearance,"Syrupy, high viscosity, high density",Quality Complaint,Product Quality,Off Colour / Appearance,Syrupy
Quality Complaint,Products,Product Quality,Colour/ Appearance,Too pulpy (when expected limited pulp or no pulp),Quality Complaint,Product Quality,Off Colour / Appearance,Too Pulpy (When Expected Limited Pulp or no Pulp)
Quality Complaint,Products,Product Quality,Colour/ Appearance,Yellow ( normally if transparent is expected),Quality Complaint,Product Quality,Off Colour / Appearance,Yellow (Normally if Transparent is Expected)
Quality Complaint,Products,Product Quality,Taste/ Odor,Acidic,Quality Complaint,Product Quality,Off Taste / Odour,Acidic
Quality Complaint,Products,Product Quality,Taste/ Odor,Another branded product,Quality Complaint,Product Quality,Off Taste / Odour,Another Branded Product
Quality Complaint,Products,Product Quality,Taste/ Odor,Bad odor/taste or off odor/taste not identified,Quality Complaint,Product Quality,Off Taste / Odour,Bad Odor / Taste or off Odor / Taste not Identified
Quality Complaint,Products,Product Quality,Taste/ Odor,"Chemical like (detergent, alcohol, etc..)",Quality Complaint,Product Quality,Off Taste / Odour,Chemical Like
Quality Complaint,Products,Product Quality,Taste/ Odor,Chlorine,Quality Complaint,Product Quality,Off Taste / Odour,Chemical Like
Quality Complaint,Products,Product Quality,Taste/ Odor,Fermented,Quality Complaint,Product Quality,Off Taste / Odour,Fermented
Quality Complaint,Products,Product Quality,Taste/ Odor,Medicinal,Quality Complaint,Product Quality,Off Taste / Odour,Medicinal
Quality Complaint,Products,Product Quality,Taste/ Odor,Metallic,Quality Complaint,Product Quality,Off Taste / Odour,Metallic
Quality Complaint,Products,Product Quality,Taste/ Odor,Musty or mouldy or earthy or stale,Quality Complaint,Product Quality,Off Taste / Odour,Musty / Mouldy / Earthy / Stale
Quality Complaint,Products,Product Quality,Taste/ Odor,Other taste/odor,Quality Complaint,Product Quality,Off Taste / Odour,Other (Off Taste / Odour Q)
Quality Complaint,Products,Product Quality,Taste/ Odor,Plastic like,Quality Complaint,Product Quality,Off Taste / Odour,Plastic Like (Off Taste / Odour Q)
Quality Complaint,Products,Product Quality,Taste/ Odor,"Rancid, oxidized",Quality Complaint,Product Quality,Off Taste / Odour,"Rancid, Oxidized"
Quality Complaint,Products,Product Quality,Taste/ Odor,Salty,Quality Complaint,Product Quality,Off Taste / Odour,Salty
Quality Complaint,Products,Product Quality,Taste/ Odor,Sulfur,Quality Complaint,Product Quality,Off Taste / Odour,Sulfur
Quality Complaint,Products,Product Quality,Taste/ Odor,Sweetness (more or less than expected),Quality Complaint,Product Quality,Off Taste / Odour,Syrupy / Too Sweet
Quality Complaint,Products,Product Quality,Taste/ Odor,"Weak taste, lack of flavor or taste",Quality Complaint,Product Quality,Off Taste / Odour,"Weak Taste, Lack of Flavor or Taste"
Quality Complaint,Products,Product Quality,Out of Age/Old Product,,Quality Complaint,Product Quality,Old Product,Post BBE
Inquiry,Corporate,Spamming,,,Spam,Spam,,
Inquiry,Corporate,Thanks - compliment,,,Thanks,Compliment,,
Thanks,Compliment,,,,Thanks,Compliment,,
